### ISSUE TITLE
Delete binaries from the repo

### ISSUE THREAD

**Issue by adg** [gobridge/gotraining#1]
https://github.com/gobridge/gotraining/blob/master/01-language_syntax/01-variables/example1/example1

These binaries should not be checked into the repo. They're platform-dependent and large. We should also set up .gitignore files to prevent them from being checked in in the future.

**Comment by ardan-bkennedy** [comment]
Absolutely, that was a mistake. Thanks for catching that,

**Comment by ardan-bkennedy** [comment]
Done

**Comment by adg** [comment]
What about adding a `.gitignore` so that it can't happen in the future? (It's very easy to do it without it.)

**Comment by ardan-bkennedy** [comment]
Yea, good idea. I will add one

**Comment by ardan-bkennedy** [comment]
@adg Do I need to add a `.gitignore` in each folder? Am I missing something that is quick and can be done in a single ignore file at the root of the project?

**Comment by adg** [comment]
You can create a single `.gitignore` at the root of the repo that lists each of the build outputs.

You can generate such a list with this command:

```
for d in $(find * -name '*.go' | xargs -n1 dirname | sort -u); do echo $d/$(basename $d); done
```

**Comment by ardan-bkennedy** [comment]
Awesome. Done and Thanks !!
