### ISSUE TITLE
helloHTTP example is bad style

### ISSUE THREAD

**Issue by adg** [gobridge/gotraining#3]
https://github.com/gobridge/gotraining/blob/master/00-slides/day1/quick/helloHTTP/helloHTTP.go#L15

```
// http://play.golang.org/p/c44Q5OiX5z
```
Is there a mechanism to keep these snippets in sync? How do we verify that they are still valid?

```
// Sample program to show off Go and check programming environment.
```

Please uses canonical godoc style throughout. Also this doc comment says nothing. This should read something like "Command hello is a web server that serves JSON-encoded greetings in two languages."

```
type (
	// hello holds a message.
	hello struct {
		Message string
	}
)
```

Factored type blocks (`type ( ... )`) are a rarely used corner of the language, and are a terrible thing to show people as their first exposure to Go.  Also, the name `hello` is a bad name; it means nothing. I suggest `type Response struct { Message string }`.

```
	http.ListenAndServe("localhost:9999", nil)
```
Check your errors! Always! Wrap this in `log.Fatal()`. The `ListenAndServe` function is documented to always return a non-nil error.

```
	err := json.NewEncoder(w).Encode(hello{"Hello World"})
	if err != nil {
		log.Println("Error encoding JSON", err)
		return
	}
```

If there's an error encoding the response, you should return an HTTP 500 status error. Instead of encoding directly to the ResponseWriter, use `json.Marshal`, check the error, and then use `w.Write` to send the response.

```
	log.Println("Sent English")
```
The log messages "Sent English" and "Sent Chinese" are unnecessary. I suggest removing them. But if you insist on keeping them, log the user's remote address so that they're a bit more informative.

**Comment by ardan-bkennedy** [comment]
Thanks for the feedback, I will fix this asap.

**Comment by corylanou** [comment]
@adg Thank you for the great feedback and taking time to look at the project.

Overall, I agree with the statements.  I did have some comments, as well as suggestions that I would like some feedback/clarification on.

> Is there a mechanism to keep these snippets in sync? How do we verify that they are still valid?

No, there is not, and it's problematic.  However, I suspect I could write a simple server that does what `go-talks.appspot.com` does and allow for something like:

```
http://go-training.appspot.com/github.com/gobridge/gotraining/blob/master/00-slides/day1/quick/helloHTTP/helloHTTP.go
```

And that would simply get the latest code (using caching likely), and redirect you to a new playground snippet with that code, as well as insert a comment at the top as to where the code originally came from.  There will be no guarantee that it will run of course, just that it's an exact copy of that code.  Thoughts?

> Instead of encoding directly to the ResponseWriter, use json.Marshal, check the error, and then use w.Write to send the response.

Is this just for readability, or is there some other concern about trying to encode directly to the writer?  My understanding was that if this fails, nothing is written, and you can still respond with an error by doing:

```go
http.Error(w, "error encoding JSON", http.StatusInternalServerError)
```

**Comment by adg** [comment]
> Thoughts?

I'd instead write a script that posts all the snippets to the playground server and then updates the files, so that it can be run offline when something changes. Otherwise you could just deploy your own version of the playground app that is aware of this specific content; that seems like more fuss though.

> Is this just for readability, or is there some other concern about trying to encode directly to the writer?

There's no guarantee that nothing will be written if `Encode` fails, and in general we should teach people to buffer responses written to an `http.ResponseWriter` when something should go wrong. The classic example is `html/template` errors being written in `200 OK` responses because the template is partially written.
